### ISSUE TITLE
use correct denom for emerynet, mainnet

### ISSUE THREAD

**Issue by 0xpatrickdev** [0xpatrickdev/agoric-vault-collateral-proposal#1]
this cannot be populated until there is a channel between agoric and stride.  using [ibc/toystatom](https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/blob/main/add-stATOM.js#L11) for now.

```zsh
# trace atom denom
$ agd query ibc-transfer denom-trace ibc/BA313C4A19DFBF943586C0387E6B11286F9E416B4DD27574E6909CABE0E342FA --node=https://agoric-rpc.polkachu.com:443
> denom_trace:
   base_denom: uatom
   path: transfer/channel-5
```

```zsh
# determine hash from atom trace
$ agd query ibc-transfer denom-hash transfer/channel-5/uatom --node=https://agoric-rpc.polkachu.com:443
> hash: BA313C4A19DFBF943586C0387E6B11286F9E416B4DD27574E6909CABE0E342FA
```

**Comment by dckc** [comment]
we could just pretend that `uphoton` (testnet ATOM) is stATOM

**Comment by 0xpatrickdev** [comment]
Per [this forum comment](https://community.agoric.com/t/onboard-statom-as-collateral/410/5) and this [chain registry pr](https://github.com/cosmos/chain-registry/pull/2689/files#diff-e4fe406aaed9a4269b93874d973adb62a588ef43db0ef9702e3fb2a6f2f164b3R16), it seems something like this will provide the denom:

```
agd query ibc-transfer denom-hash transfer/channel-59/stuatom --node=$NODE_URL
```
This is currently returning `denomination trace not found: key not found`. Curious if there is a way to determine a trace w/o sending tokens 🤔

Also see this for the `stuatom` and `statom` denoms: https://github.com/cosmos/chain-registry/blob/2c08fb52b1b585c5a24a04eb1c84fe8d2d105c92/stride/assetlist.json#L27-L51

**Comment by dckc** [comment]
fixed:

https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/blob/89fd318764e5575f528b0d38f23b33b18d8fa727/add-stATOM.js#L12

**Comment by dckc** [comment]
we've been playing with the denom lately. need to line it up

 - [x] for emerynet
 - [ ] for mainnet

seems to need a separate release for each
