### ISSUE TITLE
mainnet: replace oracleAddresses

### ISSUE THREAD

**Issue by dckc** [0xpatrickdev/agoric-vault-collateral-proposal#14]
_IOU description; meanwhile, see #3, #12_

**Comment by 0xpatrickdev** [comment]
### To Validate:

highPrioritySenders gives a good sense of who the oracle operators might be:

https://p2p-org.github.io/p2p-agoric-vstorage-viewer/#https://main.rpc.agoric.net|highPrioritySenders|.highPrioritySenders

<img width="633" alt="image" src="https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/assets/11021913/b82d6d1a-1a61-4949-a965-4198e90fada1">


Within this list, any address who used a **PushPrice invitationMaker** narrows it down.

https://bigdipper.live/agoric/transactions/18E0688EFCE78526B27E7F8250D991E5B81C9493C0A372B388250F985593AF75
<img width="1126" alt="image" src="https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/assets/11021913/bd353533-b1b4-4dc1-8cf6-1e9857327323">


Edit: h/t @otoole-brendan !
