### ISSUE TITLE
auction timing

### ISSUE THREAD

**Issue by dckc** [0xpatrickdev/agoric-vault-collateral-proposal#21]
To avoid the auction timing snafu we hit last time, we need to integrate https://github.com/Agoric/agoric-sdk/pull/8398

LMK if you find time to test it in a local chain before I do.

**Comment by dckc** [comment]
@0xpatrickdev we have one more PR coming in this area that we recommend including.

cc @turadg

**Comment by dckc** [comment]
in progress:
 - https://github.com/Agoric/agoric-sdk/pull/8452

**Comment by dckc** [comment]
8452 has landed:
> merged commit [13a758d](https://github.com/Agoric/agoric-sdk/commit/13a758d01ee151552e5d9af8b7d3fc2cb9d4961f) into master

**Comment by 0xpatrickdev** [comment]
see #22
