### ISSUE TITLE
open vault on local chain: collateral quote?

### ISSUE THREAD

**Issue by dckc** [0xpatrickdev/agoric-vault-collateral-proposal#8]
We should be sure actually creating a vault works on a local chain before trying it on devnet.

I suspect #2 and #3 make it impossible to actually create a vault using the collateral established by the proposal so far.

**Comment by dckc** [comment]
The "testing status" and "what is missing" notes in #11 look like work that's relevant here.

> I am (seemingly) able to submit oracles prices using the agops cli, but am getting a `maxDebtFor called before a collateral quote was available` error when opening an stATOM vault. This error occurs when `storedCollateralQuote` is undefined, so it seems I may be missing a step.

**Comment by dckc** [comment]
Note `"minSubmissionCount": 3` in [decentral-devnet-config.json](https://github.com/0xpatrickdev/agoric-sdk/blob/pc/statom-vault-proposal/packages/vm-config/decentral-devnet-config.json). Did you submit from 3 of the `oracleAddresses`?

In our testing, we have a little [pushPrice](https://github.com/Agoric/agoric-sdk/blob/a3d49e541a2e7b3763f16a78466d70e1ce497d4a/packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-11/env_setup.sh#L23-L48) shell function. But I think it assumes `"minSubmissionCount": 2`.

Hm. That config file also has `"initialPrice": 12.34`, which means it shouldn't be necessary to push a price before opening a vault at all.

Which config file are you/we using?

**Comment by 0xpatrickdev** [comment]
Thanks Dan, changing `minSubmissionCount` to `2` and configuring a second oracle address to test with did the trick!  I think with #11 we can mark this closed
