### ISSUE TITLE
reproducible bundles

### ISSUE THREAD

**Issue by dckc** [0xpatrickdev/agoric-vault-collateral-proposal#9]
I'd like to be able to reproduce the bundles.

How about sharing a fork/branch of agoric-sdk with your tweaks?

**Comment by dckc** [comment]
In #11 I see you shared
 https://github.com/Agoric/agoric-sdk/compare/master...0xpatrickdev:agoric-sdk:pc/statom-vault-proposal

Thanks. Here's hoping I can reproduce the bundles.

I currently see that branch is at `59581aa`

**Comment by dckc** [comment]
~~I'm not (yet) able to reproduce these bundles.~~ I'm able to match the bundles on the `feat/statom1` branch.

When I check out the [pc/statom-vault-proposal](https://github.com/0xpatrickdev/agoric-sdk/tree/pc/statom-vault-proposal) branch, `git log` tells me it's currently at `59581aa10`. I did `yarn && yarn build` and then `agoric run scripts/add-STARS.js` in `packages/inter-protocol`. ~~The resulting bundle IDs don't match what I see in the README here.~~

<details><summary>agoric run scripts/add-STARS.js log</summary>

```
$ cd packages/inter-protocol/
packages/inter-protocol$ yarn build:add-STARS-proposal
yarn run v1.22.19
$ agoric run scripts/add-STARS.js
agoric: run: running /home/connolly/projects/ag-statom/packages/inter-protocol/scripts/add-STARS.js
agoric: run: Deploy script will run with Node.js ESM
bundle-source --to /home/connolly/projects/ag-statom/packages/inter-protocol/bundles /home/connolly/projects/ag-statom/packages/zoe/src/contracts/scaledPriceAuthority.js scaledPriceAuthority
/home/connolly/projects/ag-statom/packages/inter-protocol/bundles bundle-scaledPriceAuthority.js valid: 136 files bundled at 2023-08-09T20:03:41.533Z
creating add-STARS-permit.json
creating add-STARS.js
You can now run a governance submission command like:
  agd tx gov submit-proposal swingset-core-eval add-STARS-permit.json add-STARS.js \
    --title="Enable <something>" --description="Evaluate add-STARS.js" --deposit=1000000ubld \
    --gas=auto --gas-adjustment=1.2
Remember to install bundles before submitting the proposal:
  agd tx swingset install-bundle @/home/connolly/.agoric/cache/b1-e4ba9cb60b5b59d4d4618710991fe8a503dd4a07c7f17029a342ccb41893bc961ae63bcb0e2c20e4bc2415c9755f090f7761751cdd00b85762902b357a48c5cf.json
  agd tx swingset install-bundle @/home/connolly/.agoric/cache/b1-938304530ab413804ba64aa99a73cccb6f2068c285631463f5bd7e6e42dda81bc27fc81a6976ab7907d19d5d0e31ee5a1eaa05bc7234c7d102cc0a0f3a34ff60.json

bundle-source --to /home/connolly/projects/ag-statom/packages/inter-protocol/bundles /home/connolly/projects/ag-statom/packages/inter-protocol/src/price/fluxAggregatorContract.js fluxAggregatorKit
/home/connolly/projects/ag-statom/packages/inter-protocol/bundles bundle-fluxAggregatorKit.js valid: 171 files bundled at 2023-08-09T20:03:45.185Z
creating add-STARS-oracles-permit.json
creating add-STARS-oracles.js
You can now run a governance submission command like:
  agd tx gov submit-proposal swingset-core-eval add-STARS-oracles-permit.json add-STARS-oracles.js \
    --title="Enable <something>" --description="Evaluate add-STARS-oracles.js" --deposit=1000000ubld \
    --gas=auto --gas-adjustment=1.2
Remember to install bundles before submitting the proposal:
  agd tx swingset install-bundle @/home/connolly/.agoric/cache/b1-8fb229296073327ed26d2a1ac56eda2bdc70c99d68621895a88f6cc09bce2defa3bd0894e97950e5a0696388193279c8f6b9399809611f8fec3ef5aeed355ba5.json
  agd tx swingset install-bundle @/home/connolly/.agoric/cache/b1-1c8e93cc80b28b2cf6b1252e9b6edb0253a1f962889f8a255397b43984950a263dd9c9efd82aee5744b46e7bd57ff1c733030e9f4dc8da9b355b185a59687862.json

Done in 3.41s.
```

</details>

**Comment by dckc** [comment]
ah... now I see the new bundles in the `feat/statom1` branch (dad8bda , fef112e ).

Yup! That's a match.

**Comment by dckc** [comment]
things have changed enough that I'd like to confirm, again, that I can build the bundles

**Comment by dckc** [comment]
Help? I'm unable to find the current `yarn build:add-stATOM-proposal` materials.

**Comment by 0xpatrickdev** [comment]
@dckc they are in the latest commit on #22 

https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/pull/22/commits/6deb9089d7647e185bf18ec46494005efad14869

I can merge this in and take a "devnet" release cut

**Comment by dckc** [comment]
all set on these now

**Comment by dckc** [comment]
## p.s. struggling to reproduce bundles from #69 stTIA

I was asked how do we see the code of the core-evals that ran in [#69 Enable stTIA vaults](https://agoric.explorers.guru/proposal/69).

Some of the code is there on the blockchain, but some of it is included by reference to a bundle:

```js
const manifestBundleRef = {
  bundleID:
    "b1-903e41a7c448a41b456298404a1c32c69302574209c6a5228723ed19e2dd99f2a693641196445bc27a90e19e1dfadfe6b3d9c9a93f080ffa33a70908e5af4fff",
};
```

That matches what we see here in [/bundles](https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/tree/main/bundles) as of f9f60a6, and it matches the attachment to release [2023-16-10-agoric-3](https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/releases/tag/2023-16-10-agoric-3). But the notes for that release don't detail how it was created.

The [v0.13.0-alpha3](https://github.com/dckc/agoric-vault-collateral-proposal/releases/tag/v0.13.0-alpha3) in my clone has the same bundle hash and some detailed notes on how it was constructed from [agoric-sdk at 4f9a171b79](https://github.com/Agoric/agoric-sdk/tree/4f9a171b79). But when I try to do the same thing today, I get different bundle hashes:

```console
~/projects/ag-statom/packages/builders$ agoric run scripts/inter-protocol/add-STARS.js
agoric: run: running /home/connolly/projects/ag-statom/packages/builders/scripts/inter-protocol/add-STARS.js
agoric: run: Deploy script will run with Node.js ESM
creating add-stATOM-permit.json
creating add-stATOM.js
You can now run a governance submission command like:
  agd tx gov submit-proposal swingset-core-eval add-stATOM-permit.json add-stATOM.js \
    --title="Enable <something>" --description="Evaluate add-stATOM.js" --deposit=1000000ubld \
    --gas=auto --gas-adjustment=1.2
Remember to install bundles before submitting the proposal:
  agd tx swingset install-bundle @/home/connolly/.agoric/cache/b1-1e1385adb83612c9e4192875e605f82b7e6af003d0a89d4327df370bef25060e4959d916353da9c1a098d17e78bbcbbe5bd9dbf482e23e0a5dc6e1327c8f47c7.json

creating add-stATOM-oracles-permit.json
creating add-stATOM-oracles.js
You can now run a governance submission command like:
  agd tx gov submit-proposal swingset-core-eval add-stATOM-oracles-permit.json add-stATOM-oracles.js \
    --title="Enable <something>" --description="Evaluate add-stATOM-oracles.js" --deposit=1000000ubld \
    --gas=auto --gas-adjustment=1.2
Remember to install bundles before submitting the proposal:
  agd tx swingset install-bundle @/home/connolly/.agoric/cache/b1-123afaa6788a9651193a39ad86e88c7d80883b0526c1243e201abb31ccf4b6574842030ecb39212668049d979884a8b644702c27e1174d1e9acc408cce34bc1f.json
```

For follow-up, see
 - https://github.com/endojs/endo/issues/1656
 - https://github.com/Agoric/agoric-sdk/issues/6086

cc @kriskowal

**Comment by dckc** [comment]
## agoric CLI from $PATH is the wrong one

`agoric run scripts/inter-protocol/add-STARS.js` was not the way the bundle is built; it's part of the **output** of the right command, which is `yarn run build:add-STARS-proposal`.

 - `agoric run ...` uses `agoric` from $PATH; hence who knows what agoric-sdk version
 - `yarn run ...` uses `agoric` from `node_modules/.bin`; hence the relevant agoric-sdk version

So... never mind.
